"""fixed the tabbles

Revision ID: 1b41734d4a9c
Revises: 626e0689e7e2
Create Date: 2026-01-27 13:50:32.872951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b41734d4a9c'
down_revision = '626e0689e7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_streams',
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('s3_prefix', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('stream_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('detection_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], name=op.f('detections_camera_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], name=op.f('detections_track_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detection_id', name=op.f('detections_pkey'))
    )
    op.create_table('tracks',
    sa.Column('track_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], name=op.f('tracks_camera_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', name=op.f('tracks_pkey'))
    )
    op.drop_table('camera_streams')
    # ### end Alembic commands ###
