"""add camera stream model and update camera

Revision ID: 626e0689e7e2
Revises: 1b384d0079af
Create Date: 2026-01-27 10:48:09.816782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626e0689e7e2'
down_revision = '1b384d0079af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=False))
        batch_op.drop_column('stream_key')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stream_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('is_enabled')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
